const verbs = ['embroider',
    'fasten',
    'stitch',
    'tailor',
    'baste',
    'bind',
    'piece',
    'seam',
    'tack',
    'work'];
const adjetives = ['adorable','affordable','anatomically designed',
    'asymmetrical','banded','beaded','beautiful','bloused','boho',
    'boho chic','boot cut','boxy','cushioned','cute','dainty',
    'couture','crisp','cross-stitched','comfortable','contemporary',
    'cool','classic','collared','colorful','breathable','buttoned',
    'casual','machine washable','old-fashioned','scooped-neck',
    'masculine','open-backed','sassy','medium','ribbed','rocker-style',
    'metallic','printed','retro print','modern','premium','pretty',
    'moisture-wicking','plunging','polished','odor-absorbing','patterned',
    'petite','elegant','organic','oversized','durable','easy-to-maintain',
    'eco-friendly','decorative','designer','discounted','embroidered',
    'flattering','intricate','environmentally-friendly','flexible','kids',
    'ergonomic','funky','knee length','exceptional','glamorous','knitted',
    'extra large','glitzy','layered','fabric-lined','hand-sewn','lightweight',
    'fabulous','hand-washed','long-lasting','fancy','high-waisted',
    'odor-resistant','fashionable','imported','plus size','feminine',"innovative",
    'sleek','strapless','translucent','whimsical','tunic length','zippered',
    'vintage','waist-slimming','water-resistant','trendy','unique','versatile',
    'textured','tight','timeless','stylish','synthetic','tailored','stitched',
    'stretchy','stunning','sophisticated','sporty','standard-fit','skinny-fit',
    'slouchy','small','short sleeve','show-stopping','silky','Empire waistline',
    'cushioned','Printed','V-neck','crewneck','patterned','attire','sleeveless',
    'Solid blue','best fit','short-sleeved','Paisley','color-washed','long-sleeved',
    'floral','crochet','street fashion','polka-dotted','designer','princess seams',
    'plaid','evening wear','neckline','striped','ethnic','lifestyle','checked',
    'jagged edge','layering','French hem','spotted','stylish','tailor-made',
    'see-through','slinky','sloppy','revealing','ruched','scooped','boat-neck',
    'off-shoulder','pinstripe','gaudy','loose-fitting','open-necked','flattering',
    'formal','glamorous','dressy','fitted','flare','close-fitting','comfortable',
    'cut-off','casual','brief','clinging','A-line','backless','baggy'

];
const clothes = ['Sweater',
    'Dress',
    'Hoodies',
    'T-shirt',
    'Flip-flops',
    'Shorts',
    'Skirt',
    'Jeans',
    'Shoes',
    'Coat',
    'High heels',
    'Suit',
    'Cap',
    'Socks',
    'Shirt',
    'Bra',
    'Scarf',
    'Swimsuit',
    'Hat',
    'Gloves',
    'Jacket',
    'Long coat',
    'Boots',
    'Sunglasses',
    'Tie',
    'Polo shirt',
    'Leather jackets'
    ];

export {adjetives, verbs, clothes};

